services:
  apache:
    build: ./
    container_name: apache
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/html
#   mariadb:
#     image: mariadb:latest
#     container_name: mariadb
#     environment:
#       MYSQL_ROOT_PASSWORD: nein
#       MYSQL_DATABASE: pokedex
#       MYSQL_USER: phpstorm
#       MYSQL_PASSWORD: phpp@ssw0rt
#     ports:
#       - "3306:3306"
#     restart: always
#     volumes:
#       - mariadb_data:/var/lib/mysql
#   adminer:
#       image: adminer
#       restart: always
#       ports:
#             - "8080:8080"

# volumes:
#   mariadb_data: